[package]
name = "worldgen-site"
version = "0.1.0"
authors = ["Samuel Sleight <samuel.sleight@gmail.com>"]

[dependencies]
rocket = { git = "https://github.com/SergioBenitez/Rocket"}
rocket_contrib = { git = "https://github.com/SergioBenitez/Rocket"}
